export const HUEMINT_TEMPLATE_CATALOG = Object.freeze([
  { category: 'Brand', slug: 'brand-1', label: '1 Color' },
  { category: 'Brand', slug: 'brand-2', label: '2 Colors' },
  { category: 'Brand', slug: 'brand-3', label: '3 Colors' },
  { category: 'Brand', slug: 'brand-intersection', label: 'Intersection' },
  { category: 'Website', slug: 'website-magazine', label: 'Magazine' },
  { category: 'Website', slug: 'website-monochrome', label: 'Monochrome' },
  { category: 'Website', slug: 'website-1', label: '1 Accent' },
  { category: 'Website', slug: 'website-2', label: '2 Accents' },
  { category: 'Website', slug: 'website-3', label: '3 Accents' },
  { category: 'Gradient', slug: 'gradient-2', label: '2 Colors' },
  { category: 'Gradient', slug: 'gradient-3', label: '3 Colors' },
  { category: 'Gradient', slug: 'gradient-4', label: '4 Colors' },
  { category: 'Gradient', slug: 'gradient-5', label: '5 Colors' },
  { category: 'Gradient', slug: 'gradient-6', label: '6 Colors' },
  { category: 'Gradient', slug: 'gradient-7', label: '7 Colors' },
  { category: 'Gradient', slug: 'gradient-8', label: '8 Colors' },
  { category: 'Gradient', slug: 'gradient-9', label: '9 Colors' },
  { category: 'Gradient', slug: 'gradient-10', label: '10 Colors' },
  { category: 'Gradient + Background', slug: 'back-gradient-2', label: '2 Colors' },
  { category: 'Gradient + Background', slug: 'back-gradient-3', label: '3 Colors' },
  { category: 'Gradient + Background', slug: 'back-gradient-4', label: '4 Colors' },
  { category: 'Gradient + Background', slug: 'back-gradient-5', label: '5 Colors' },
  { category: 'Illustration', slug: 'illustration-1', label: 'Illustration 1' },
  { category: 'Illustration', slug: 'illustration-2', label: 'Illustration 2' },
  { category: 'Illustration', slug: 'illustration-3', label: 'Illustration 3' },
  { category: 'Bootstrap', slug: 'bootstrap-basic', label: 'Basic' },
  { category: 'Bootstrap', slug: 'bootstrap-plus', label: 'Plus' }
]);
