// Generated by npm run huemint:browser-corpus. Do not edit by hand.
window.HUEMINT_TEMPLATE_CATALOG = [
  {
    "category": "Brand",
    "slug": "brand-1",
    "label": "1 Color",
    "numColors": 2
  },
  {
    "category": "Brand",
    "slug": "brand-2",
    "label": "2 Colors",
    "numColors": 3
  },
  {
    "category": "Brand",
    "slug": "brand-3",
    "label": "3 Colors",
    "numColors": 4
  },
  {
    "category": "Brand",
    "slug": "brand-intersection",
    "label": "Intersection",
    "numColors": 4
  },
  {
    "category": "Website",
    "slug": "website-magazine",
    "label": "Magazine",
    "numColors": 4
  },
  {
    "category": "Website",
    "slug": "website-monochrome",
    "label": "Monochrome",
    "numColors": 2
  },
  {
    "category": "Website",
    "slug": "website-1",
    "label": "1 Accent",
    "numColors": 3
  },
  {
    "category": "Website",
    "slug": "website-2",
    "label": "2 Accents",
    "numColors": 4
  },
  {
    "category": "Website",
    "slug": "website-3",
    "label": "3 Accents",
    "numColors": 6
  },
  {
    "category": "Gradient",
    "slug": "gradient-2",
    "label": "2 Colors",
    "numColors": 2
  },
  {
    "category": "Gradient",
    "slug": "gradient-3",
    "label": "3 Colors",
    "numColors": 3
  },
  {
    "category": "Gradient",
    "slug": "gradient-4",
    "label": "4 Colors",
    "numColors": 4
  },
  {
    "category": "Gradient",
    "slug": "gradient-5",
    "label": "5 Colors",
    "numColors": 5
  },
  {
    "category": "Gradient",
    "slug": "gradient-6",
    "label": "6 Colors",
    "numColors": 6
  },
  {
    "category": "Gradient",
    "slug": "gradient-7",
    "label": "7 Colors",
    "numColors": 7
  },
  {
    "category": "Gradient",
    "slug": "gradient-8",
    "label": "8 Colors",
    "numColors": 8
  },
  {
    "category": "Gradient",
    "slug": "gradient-9",
    "label": "9 Colors",
    "numColors": 9
  },
  {
    "category": "Gradient",
    "slug": "gradient-10",
    "label": "10 Colors",
    "numColors": 10
  },
  {
    "category": "Gradient + Background",
    "slug": "back-gradient-2",
    "label": "2 Colors",
    "numColors": 3
  },
  {
    "category": "Gradient + Background",
    "slug": "back-gradient-3",
    "label": "3 Colors",
    "numColors": 4
  },
  {
    "category": "Gradient + Background",
    "slug": "back-gradient-4",
    "label": "4 Colors",
    "numColors": 5
  },
  {
    "category": "Gradient + Background",
    "slug": "back-gradient-5",
    "label": "5 Colors",
    "numColors": 6
  },
  {
    "category": "Illustration",
    "slug": "illustration-1",
    "label": "Illustration 1",
    "numColors": 6
  },
  {
    "category": "Illustration",
    "slug": "illustration-2",
    "label": "Illustration 2",
    "numColors": 8
  },
  {
    "category": "Illustration",
    "slug": "illustration-3",
    "label": "Illustration 3",
    "numColors": 11
  },
  {
    "category": "Bootstrap",
    "slug": "bootstrap-basic",
    "label": "Basic",
    "numColors": 6
  },
  {
    "category": "Bootstrap",
    "slug": "bootstrap-plus",
    "label": "Plus",
    "numColors": 9
  }
];
window.HUEMINT_LOCAL_CORPUS = [
  {
    "id": "0366bd836068359a57c5",
    "colors": [
      "#fbfffd",
      "#009ce8",
      "#2055b8"
    ],
    "score": -5.5269646644592285,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-2",
    "source": "huemint-back-gradient-2"
  },
  {
    "id": "80b5917575ef1509c00f",
    "colors": [
      "#f64445",
      "#efe9dc",
      "#f9c73d"
    ],
    "score": -6.742755889892578,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-2",
    "source": "huemint-back-gradient-2"
  },
  {
    "id": "a7047fb192bd286d90c4",
    "colors": [
      "#248f90",
      "#f4efea",
      "#f0a737"
    ],
    "score": -7.508354663848877,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-2",
    "source": "huemint-back-gradient-2"
  },
  {
    "id": "c3e82370d16b1ee1240f",
    "colors": [
      "#fffeff",
      "#2acbb8",
      "#958f5e"
    ],
    "score": -7.36067533493042,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-2",
    "source": "huemint-back-gradient-2"
  },
  {
    "id": "eb24314bb7d62820827b",
    "colors": [
      "#aec7c0",
      "#fef3ed",
      "#f95f52"
    ],
    "score": -7.746006965637207,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-2",
    "source": "huemint-back-gradient-2"
  },
  {
    "id": "15a029b06be73571eda7",
    "colors": [
      "#ffe8e3",
      "#c44a51",
      "#a22d2b",
      "#5b1713"
    ],
    "score": -6.099400520324707,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-3",
    "source": "huemint-back-gradient-3"
  },
  {
    "id": "7e9c0353eecf63ad7419",
    "colors": [
      "#f6edec",
      "#8773ce",
      "#5e579a",
      "#232b82"
    ],
    "score": -6.69452428817749,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-3",
    "source": "huemint-back-gradient-3"
  },
  {
    "id": "bc4d64bcd330195ac9b1",
    "colors": [
      "#f6f5f7",
      "#f4725c",
      "#c84535",
      "#6d2d30"
    ],
    "score": -7.104592800140381,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-3",
    "source": "huemint-back-gradient-3"
  },
  {
    "id": "c0921128f201e0c0264b",
    "colors": [
      "#271f17",
      "#aa867d",
      "#beab9b",
      "#e9d8cd"
    ],
    "score": -6.5895676612854,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-3",
    "source": "huemint-back-gradient-3"
  },
  {
    "id": "dba0bc99887533d86109",
    "colors": [
      "#090000",
      "#665e2b",
      "#8e732a",
      "#cba55f"
    ],
    "score": -6.503105163574219,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-3",
    "source": "huemint-back-gradient-3"
  },
  {
    "id": "2d1ed348fd081ba7bd2d",
    "colors": [
      "#f4f2f4",
      "#a26ca1",
      "#675099",
      "#584471",
      "#3c3d5b"
    ],
    "score": -6.078516960144043,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-4",
    "source": "huemint-back-gradient-4"
  },
  {
    "id": "6064747e15c66f5306f1",
    "colors": [
      "#171820",
      "#6d6156",
      "#a79171",
      "#b5a196",
      "#cdcebe"
    ],
    "score": -5.685906887054443,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-4",
    "source": "huemint-back-gradient-4"
  },
  {
    "id": "7ffc31e9f9227e182295",
    "colors": [
      "#272727",
      "#a63760",
      "#ea4c89",
      "#f190a4",
      "#f9bad3"
    ],
    "score": -5.556625843048096,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-4",
    "source": "huemint-back-gradient-4"
  },
  {
    "id": "a411f01a34186492b64e",
    "colors": [
      "#ffffff",
      "#748794",
      "#59646e",
      "#455662",
      "#58384c"
    ],
    "score": -6.478032112121582,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-4",
    "source": "huemint-back-gradient-4"
  },
  {
    "id": "cfe3f752ea06d63d7651",
    "colors": [
      "#131616",
      "#006551",
      "#569d80",
      "#60a194",
      "#aae4db"
    ],
    "score": -7.313745975494385,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-4",
    "source": "huemint-back-gradient-4"
  },
  {
    "id": "32fe056623a412e7a71d",
    "colors": [
      "#2b2a68",
      "#c43168",
      "#e56c8a",
      "#efadb9",
      "#f2d1da",
      "#fdfbfa"
    ],
    "score": -6.247751235961914,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-5",
    "source": "huemint-back-gradient-5"
  },
  {
    "id": "6cd338eb86978cd32475",
    "colors": [
      "#b0d7f5",
      "#007ca2",
      "#01657d",
      "#244457",
      "#062a49",
      "#0c0003"
    ],
    "score": -7.582636833190918,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-5",
    "source": "huemint-back-gradient-5"
  },
  {
    "id": "aa26d0010ef9ef206612",
    "colors": [
      "#eb3264",
      "#f3dbdc",
      "#ffffff",
      "#acc4ad",
      "#629265",
      "#5b7850"
    ],
    "score": -8.336761474609375,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-5",
    "source": "huemint-back-gradient-5"
  },
  {
    "id": "c8ee63ad8134acf3d8db",
    "colors": [
      "#0d1416",
      "#986d2e",
      "#e59c4a",
      "#f5bc7f",
      "#f2cd6d",
      "#e8e9c4"
    ],
    "score": -7.012887477874756,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-5",
    "source": "huemint-back-gradient-5"
  },
  {
    "id": "fd4c427bdebed96466bf",
    "colors": [
      "#fdfffd",
      "#e74a87",
      "#af3a68",
      "#901d4a",
      "#581a4e",
      "#39124e"
    ],
    "score": -5.462091445922852,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "back-gradient-5",
    "source": "huemint-back-gradient-5"
  },
  {
    "id": "30573e590340f2b7feb1",
    "colors": [
      "#d4dff4",
      "#ffffff",
      "#010a25",
      "#16824a",
      "#0055dd",
      "#4b7bbb"
    ],
    "score": -7.214953422546387,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-basic",
    "source": "huemint-bootstrap-basic"
  },
  {
    "id": "4c5b6b6d5bf68331e271",
    "colors": [
      "#f0d640",
      "#ffffff",
      "#27211f",
      "#5a3b1d",
      "#ac5725",
      "#434b68"
    ],
    "score": -6.694726467132568,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-basic",
    "source": "huemint-bootstrap-basic"
  },
  {
    "id": "72960448f60d9e03edd9",
    "colors": [
      "#fdd9d6",
      "#ffffff",
      "#000205",
      "#664437",
      "#3b5159",
      "#e54f29"
    ],
    "score": -7.161021709442139,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-basic",
    "source": "huemint-bootstrap-basic"
  },
  {
    "id": "7a4609484a2476de880f",
    "colors": [
      "#fff8cd",
      "#ffffff",
      "#28ee00",
      "#f20064",
      "#ab2be3",
      "#fb4545"
    ],
    "score": -7.855865001678467,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-basic",
    "source": "huemint-bootstrap-basic"
  },
  {
    "id": "c3adda1a25504efd1d21",
    "colors": [
      "#eaead5",
      "#ffffff",
      "#060000",
      "#2c5587",
      "#efb6b1",
      "#e11011"
    ],
    "score": -7.60637903213501,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-basic",
    "source": "huemint-bootstrap-basic"
  },
  {
    "id": "33705a510636beacedf3",
    "colors": [
      "#f9f900",
      "#ffffff",
      "#2d0816",
      "#52008f",
      "#ad03fe",
      "#ff28ff",
      "#17fb11",
      "#12b200",
      "#a7b5b0"
    ],
    "score": -7.1226420402526855,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-plus",
    "source": "huemint-bootstrap-plus"
  },
  {
    "id": "3a16844a26e53b96a3b5",
    "colors": [
      "#e4e6ec",
      "#ffffff",
      "#031925",
      "#9c0b0d",
      "#ee0d0d",
      "#fc5f50",
      "#1b3b54",
      "#5865c3",
      "#afabbc"
    ],
    "score": -6.149626731872559,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-plus",
    "source": "huemint-bootstrap-plus"
  },
  {
    "id": "4637d19378a0691b4da6",
    "colors": [
      "#b7e0d5",
      "#ffffff",
      "#110706",
      "#005343",
      "#057f6e",
      "#56c470",
      "#f28a93",
      "#299d5d",
      "#59bd92"
    ],
    "score": -7.275993824005127,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-plus",
    "source": "huemint-bootstrap-plus"
  },
  {
    "id": "9e5109ee9994b17859aa",
    "colors": [
      "#75bf35",
      "#ffffff",
      "#0a090a",
      "#1f2814",
      "#506c18",
      "#3b4b0c",
      "#0c2939",
      "#374f49",
      "#679450"
    ],
    "score": -6.543491363525391,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-plus",
    "source": "huemint-bootstrap-plus"
  },
  {
    "id": "dd200abf0faae07d0b47",
    "colors": [
      "#f4e5c0",
      "#ffffff",
      "#0d0e0f",
      "#22c224",
      "#5c883d",
      "#8eb736",
      "#593a3f",
      "#a75f58",
      "#36d4f7"
    ],
    "score": -6.932401657104492,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "bootstrap-plus",
    "source": "huemint-bootstrap-plus"
  },
  {
    "id": "6ed43f858d810988cf7f",
    "colors": [
      "#eaebec",
      "#252120"
    ],
    "score": -5.087867736816406,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-1",
    "source": "huemint-brand-1"
  },
  {
    "id": "4a4b35be2ffe24b17954",
    "colors": [
      "#fffbff",
      "#252758"
    ],
    "score": -5.19597053527832,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-1",
    "source": "huemint-brand-1"
  },
  {
    "id": "5254f6e247c020a4a4a9",
    "colors": [
      "#030100",
      "#ecc206"
    ],
    "score": -5.397857666015625,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-1",
    "source": "huemint-brand-1"
  },
  {
    "id": "a27c246daded96902b95",
    "colors": [
      "#f7fdf5",
      "#3b2d27"
    ],
    "score": -5.764172077178955,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-1",
    "source": "huemint-brand-1"
  },
  {
    "id": "a45f4fe08294423aab56",
    "colors": [
      "#373533",
      "#dfdfda"
    ],
    "score": -5.596685409545898,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-1",
    "source": "huemint-brand-1"
  },
  {
    "id": "10bfe8b7766787f6e90e",
    "colors": [
      "#000005",
      "#af995f",
      "#00decf"
    ],
    "score": -8.405924797058105,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-2",
    "source": "huemint-brand-2"
  },
  {
    "id": "7c85bca9291a893ceac1",
    "colors": [
      "#b44905",
      "#db521b",
      "#fbfffc"
    ],
    "score": -8.756343841552734,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-2",
    "source": "huemint-brand-2"
  },
  {
    "id": "92eaf62ddf0ed56ee398",
    "colors": [
      "#fffeff",
      "#69d7d2",
      "#5f4f2c"
    ],
    "score": -7.706789493560791,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-2",
    "source": "huemint-brand-2"
  },
  {
    "id": "e26fc46d33c7c6b953f4",
    "colors": [
      "#f6f6f2",
      "#281b2d",
      "#c05c82"
    ],
    "score": -8.65188217163086,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-2",
    "source": "huemint-brand-2"
  },
  {
    "id": "e3d5c0271ce4944d4296",
    "colors": [
      "#fffffe",
      "#681d03",
      "#269232"
    ],
    "score": -6.7559332847595215,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-2",
    "source": "huemint-brand-2"
  },
  {
    "id": "1015556dc0c86358361c",
    "colors": [
      "#142c3a",
      "#f2efe0",
      "#bd6542",
      "#2c743b"
    ],
    "score": -7.729068756103516,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-3",
    "source": "huemint-brand-3"
  },
  {
    "id": "339290aeee16895d2d5d",
    "colors": [
      "#fffffc",
      "#363645",
      "#fe2b3f",
      "#d1a6ad"
    ],
    "score": -6.120809555053711,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-3",
    "source": "huemint-brand-3"
  },
  {
    "id": "8beaf15d3db6b3f8ce4c",
    "colors": [
      "#fbfdff",
      "#47205c",
      "#e55a28",
      "#ffd072"
    ],
    "score": -8.471505165100098,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-3",
    "source": "huemint-brand-3"
  },
  {
    "id": "b845358c6a710fe42d30",
    "colors": [
      "#b02235",
      "#98dbae",
      "#f7e4e4",
      "#291718"
    ],
    "score": -8.465232849121094,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-3",
    "source": "huemint-brand-3"
  },
  {
    "id": "e9b8e32e2cddaa4457fe",
    "colors": [
      "#393532",
      "#f3e7e7",
      "#f26959",
      "#c176ae"
    ],
    "score": -8.43523120880127,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-3",
    "source": "huemint-brand-3"
  },
  {
    "id": "9fd774d9375cbe7c2c27",
    "colors": [
      "#070823",
      "#00eafd",
      "#0068c6",
      "#06052d"
    ],
    "score": -8.239997863769531,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-intersection",
    "source": "huemint-brand-intersection"
  },
  {
    "id": "ca57a9f92a90f7f34ba6",
    "colors": [
      "#fbb8bc",
      "#15213a",
      "#5d57ab",
      "#6bbbfb"
    ],
    "score": -8.824399948120117,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-intersection",
    "source": "huemint-brand-intersection"
  },
  {
    "id": "f44889793e3e72302e10",
    "colors": [
      "#003a53",
      "#f3d995",
      "#61a883",
      "#428395"
    ],
    "score": -8.785569190979004,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-intersection",
    "source": "huemint-brand-intersection"
  },
  {
    "id": "fd0e2c4dec24757a7610",
    "colors": [
      "#fdd90b",
      "#312a22",
      "#fb2020",
      "#efeff1"
    ],
    "score": -7.537229537963867,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-intersection",
    "source": "huemint-brand-intersection"
  },
  {
    "id": "ffbf82cde9a37093e388",
    "colors": [
      "#620000",
      "#e6ae16",
      "#c46450",
      "#2e2826"
    ],
    "score": -8.82790470123291,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "brand-intersection",
    "source": "huemint-brand-intersection"
  },
  {
    "id": "00762480253d7c717375",
    "colors": [
      "#070708",
      "#374349",
      "#162935",
      "#364955",
      "#4d6171",
      "#497091",
      "#879cb7",
      "#6d8db0",
      "#97b8db",
      "#b5b4ce"
    ],
    "score": -6.062587261199951,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-10",
    "source": "huemint-gradient-10"
  },
  {
    "id": "35b8364ada7a247e6732",
    "colors": [
      "#e5e4da",
      "#d7cca9",
      "#babf4b",
      "#8e9c59",
      "#8b7b4c",
      "#727546",
      "#635836",
      "#655a29",
      "#53482f",
      "#4c3614"
    ],
    "score": -5.882476806640625,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-10",
    "source": "huemint-gradient-10"
  },
  {
    "id": "d37e800eebba475c741c",
    "colors": [
      "#18132e",
      "#0f0703",
      "#292932",
      "#602e2f",
      "#595456",
      "#944c3a",
      "#995d59",
      "#a06d5a",
      "#bc8470",
      "#cdb7ae"
    ],
    "score": -5.928596019744873,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-10",
    "source": "huemint-gradient-10"
  },
  {
    "id": "e76b564d24b2749b0fd9",
    "colors": [
      "#100906",
      "#2e1807",
      "#3d2e20",
      "#615531",
      "#686353",
      "#8e7254",
      "#a5936d",
      "#ce945a",
      "#a7a3a3",
      "#d3a36c"
    ],
    "score": -6.348697662353516,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-10",
    "source": "huemint-gradient-10"
  },
  {
    "id": "eaebb1646b58f0031c08",
    "colors": [
      "#fffffc",
      "#d8b199",
      "#e1d8d8",
      "#b5b096",
      "#a7896b",
      "#87765b",
      "#646358",
      "#524339",
      "#955933",
      "#382e25"
    ],
    "score": -5.8924150466918945,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-10",
    "source": "huemint-gradient-10"
  },
  {
    "id": "10764f6c06c76393d3fe",
    "colors": [
      "#f7faf7",
      "#b6bee6"
    ],
    "score": -6.318687438964844,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-2",
    "source": "huemint-gradient-2"
  },
  {
    "id": "97e38a94711a1dbbd170",
    "colors": [
      "#fefeff",
      "#555557"
    ],
    "score": -4.733591556549072,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-2",
    "source": "huemint-gradient-2"
  },
  {
    "id": "c602d0d5dd4b401ad839",
    "colors": [
      "#fffffd",
      "#e44839"
    ],
    "score": -6.777695178985596,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-2",
    "source": "huemint-gradient-2"
  },
  {
    "id": "f43ca526def40bb9a308",
    "colors": [
      "#fefbef",
      "#cb4e3b"
    ],
    "score": -6.342942237854004,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-2",
    "source": "huemint-gradient-2"
  },
  {
    "id": "ffa8d8e445f2f523234b",
    "colors": [
      "#181818",
      "#bb8731"
    ],
    "score": -5.88342809677124,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-2",
    "source": "huemint-gradient-2"
  },
  {
    "id": "c23f2078b1a7ff7ef763",
    "colors": [
      "#fcffff",
      "#b1d1f8",
      "#48abf7"
    ],
    "score": -4.375801086425781,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-3",
    "source": "huemint-gradient-3"
  },
  {
    "id": "2f138d9727534b9d7428",
    "colors": [
      "#00adaf",
      "#177a95",
      "#18516b"
    ],
    "score": -5.619594573974609,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-3",
    "source": "huemint-gradient-3"
  },
  {
    "id": "4ac0886d0c6c738b1f7f",
    "colors": [
      "#5a9c41",
      "#6a9228",
      "#3a6639"
    ],
    "score": -6.864865779876709,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-3",
    "source": "huemint-gradient-3"
  },
  {
    "id": "bf34f3fb049c747fb7a5",
    "colors": [
      "#fcfffc",
      "#dcd7d2",
      "#a39e99"
    ],
    "score": -5.9499592781066895,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-3",
    "source": "huemint-gradient-3"
  },
  {
    "id": "f07dea472450168ac244",
    "colors": [
      "#fbf9fc",
      "#cbcfce",
      "#cdba8b"
    ],
    "score": -6.645656108856201,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-3",
    "source": "huemint-gradient-3"
  },
  {
    "id": "10f1853733c6386f996f",
    "colors": [
      "#fffefb",
      "#daede1",
      "#63d19e",
      "#258d5b"
    ],
    "score": -5.884392738342285,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-4",
    "source": "huemint-gradient-4"
  },
  {
    "id": "4413f5c05a11e42b35bf",
    "colors": [
      "#fffffe",
      "#c8e6db",
      "#a2cbbe",
      "#428773"
    ],
    "score": -4.776498794555664,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-4",
    "source": "huemint-gradient-4"
  },
  {
    "id": "2c009ca385665f8ef8c0",
    "colors": [
      "#fdfdfd",
      "#97d5f0",
      "#59aef9",
      "#677bc6"
    ],
    "score": -7.160653591156006,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-4",
    "source": "huemint-gradient-4"
  },
  {
    "id": "8b95d1ad8bfe5616879c",
    "colors": [
      "#ffd6df",
      "#e0b2d9",
      "#9f7cbb",
      "#71588f"
    ],
    "score": -6.002945899963379,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-4",
    "source": "huemint-gradient-4"
  },
  {
    "id": "c2e40f5f9c6199c78eb8",
    "colors": [
      "#fafaf7",
      "#a9d3c4",
      "#5f968d",
      "#2e7686"
    ],
    "score": -6.028827667236328,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-4",
    "source": "huemint-gradient-4"
  },
  {
    "id": "d726c47083c45b2167bf",
    "colors": [
      "#f2f9f3",
      "#f2e2ca",
      "#cc4d7c",
      "#e85790",
      "#8f1540"
    ],
    "score": -6.136955738067627,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-5",
    "source": "huemint-gradient-5"
  },
  {
    "id": "4ce540ede48c44f4db5f",
    "colors": [
      "#e9eced",
      "#e0d9cf",
      "#b3a39b",
      "#f40012",
      "#ba1f1f"
    ],
    "score": -6.696174144744873,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-5",
    "source": "huemint-gradient-5"
  },
  {
    "id": "a0ab02446eb8973784b2",
    "colors": [
      "#d1b999",
      "#cd8b2f",
      "#b06a19",
      "#793b13",
      "#22120e"
    ],
    "score": -7.086160659790039,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-5",
    "source": "huemint-gradient-5"
  },
  {
    "id": "b0110af976bb97e72387",
    "colors": [
      "#0b1723",
      "#16315b",
      "#1e4cdd",
      "#0b6ee4",
      "#559afb"
    ],
    "score": -6.406231880187988,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-5",
    "source": "huemint-gradient-5"
  },
  {
    "id": "f173c7a7079686691627",
    "colors": [
      "#18280b",
      "#0f2602",
      "#487033",
      "#738c54",
      "#9ea262"
    ],
    "score": -6.30911111831665,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-5",
    "source": "huemint-gradient-5"
  },
  {
    "id": "132fbcee081d57677f40",
    "colors": [
      "#ac0f39",
      "#d21644",
      "#ffa8bd",
      "#f621f4",
      "#ee61b5",
      "#ffe7f6"
    ],
    "score": -7.744755744934082,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-6",
    "source": "huemint-gradient-6"
  },
  {
    "id": "6bd473222cd79d95ef35",
    "colors": [
      "#e7c32b",
      "#fce0b1",
      "#e9a054",
      "#e68a31",
      "#e7692f",
      "#b03824"
    ],
    "score": -7.450897693634033,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-6",
    "source": "huemint-gradient-6"
  },
  {
    "id": "84f363769b9ef350d5c2",
    "colors": [
      "#f7edeb",
      "#dad2f1",
      "#a0cffc",
      "#55abf5",
      "#5772e8",
      "#3364c0"
    ],
    "score": -7.271123886108398,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-6",
    "source": "huemint-gradient-6"
  },
  {
    "id": "aac886bbdf028d02d81f",
    "colors": [
      "#e8eef1",
      "#665d66",
      "#8e7480",
      "#a79da8",
      "#9351ef",
      "#7355ed"
    ],
    "score": -7.413488864898682,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-6",
    "source": "huemint-gradient-6"
  },
  {
    "id": "d7d4e4c1be4c0aee95bc",
    "colors": [
      "#fafafa",
      "#f7c4c4",
      "#fc97bb",
      "#fb74a8",
      "#ea3d6f",
      "#9f254f"
    ],
    "score": -5.711219310760498,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-6",
    "source": "huemint-gradient-6"
  },
  {
    "id": "3f85decc50f03a1e42fc",
    "colors": [
      "#0c0908",
      "#2c0f0a",
      "#422c09",
      "#5c5f23",
      "#7e7f35",
      "#a0a636",
      "#bca332"
    ],
    "score": -4.965347766876221,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-7",
    "source": "huemint-gradient-7"
  },
  {
    "id": "846b44204dccf690da5a",
    "colors": [
      "#000408",
      "#002335",
      "#153d51",
      "#007496",
      "#4093ad",
      "#238eb5",
      "#8ab6db"
    ],
    "score": -5.865560531616211,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-7",
    "source": "huemint-gradient-7"
  },
  {
    "id": "b5131c2462a45446b327",
    "colors": [
      "#010002",
      "#2f190d",
      "#603306",
      "#af5323",
      "#db6c1a",
      "#ef9421",
      "#e8a62a"
    ],
    "score": -6.044743537902832,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-7",
    "source": "huemint-gradient-7"
  },
  {
    "id": "c8a2aeb1b69b83abe70b",
    "colors": [
      "#290706",
      "#171111",
      "#092a19",
      "#00463c",
      "#18685a",
      "#3c9572",
      "#52b546"
    ],
    "score": -6.782569885253906,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-7",
    "source": "huemint-gradient-7"
  },
  {
    "id": "d221c6896216b5a5144a",
    "colors": [
      "#2a0f10",
      "#542a24",
      "#6a4d41",
      "#8a6858",
      "#b59479",
      "#cbb6a7",
      "#cdcfb2"
    ],
    "score": -6.698018550872803,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-7",
    "source": "huemint-gradient-7"
  },
  {
    "id": "36c0ff551e1879678a28",
    "colors": [
      "#ebe5c9",
      "#a3b095",
      "#cac2b0",
      "#8f8e7a",
      "#616552",
      "#7892b0",
      "#284d97",
      "#3f4456"
    ],
    "score": -6.972533702850342,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-8",
    "source": "huemint-gradient-8"
  },
  {
    "id": "634aad489088aad1d691",
    "colors": [
      "#fffbfc",
      "#e0dfd5",
      "#00da5f",
      "#9da79e",
      "#24b35d",
      "#79827b",
      "#00740c",
      "#1f6536"
    ],
    "score": -7.279138088226318,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-8",
    "source": "huemint-gradient-8"
  },
  {
    "id": "699772c03a1f845a7df3",
    "colors": [
      "#f7d7d8",
      "#fbf8f5",
      "#d39996",
      "#31333c",
      "#ae9499",
      "#6f555e",
      "#8d5e4f",
      "#5f3d3a"
    ],
    "score": -7.302013874053955,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-8",
    "source": "huemint-gradient-8"
  },
  {
    "id": "ae70e31703c921bd5dbe",
    "colors": [
      "#fbf8fc",
      "#b8cbe3",
      "#d1d7e4",
      "#96b4d3",
      "#7190c3",
      "#6a6ca3",
      "#4c2d8d",
      "#35466c"
    ],
    "score": -6.675629615783691,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-8",
    "source": "huemint-gradient-8"
  },
  {
    "id": "ce8c2d1d7817a3f07707",
    "colors": [
      "#f6f9f6",
      "#dbe9f3",
      "#afd1d8",
      "#9ab3cc",
      "#718cab",
      "#4e708f",
      "#435c78",
      "#0e51ac"
    ],
    "score": -5.322628498077393,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-8",
    "source": "huemint-gradient-8"
  },
  {
    "id": "2a42fecc53682b930ffd",
    "colors": [
      "#122b2a",
      "#081710",
      "#2d5c59",
      "#307685",
      "#596255",
      "#609e9a",
      "#a1aba4",
      "#909c5b",
      "#c4bca5"
    ],
    "score": -6.608180046081543,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-9",
    "source": "huemint-gradient-9"
  },
  {
    "id": "5813e48b4ef758dea649",
    "colors": [
      "#f2f1f1",
      "#cfd2d3",
      "#afafae",
      "#8e9390",
      "#d79e49",
      "#ab7e34",
      "#644f33",
      "#6f5534",
      "#2c270c"
    ],
    "score": -6.551566123962402,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-9",
    "source": "huemint-gradient-9"
  },
  {
    "id": "d21cf0f65d5c212a2652",
    "colors": [
      "#0d0805",
      "#313130",
      "#006cb0",
      "#304864",
      "#4967a4",
      "#7093d1",
      "#89aaca",
      "#9aa5cd",
      "#91b6e3"
    ],
    "score": -6.950237274169922,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-9",
    "source": "huemint-gradient-9"
  },
  {
    "id": "d649a34ab454ffcf40b2",
    "colors": [
      "#fdfbfa",
      "#dedada",
      "#e8d3ad",
      "#d0af91",
      "#c99e72",
      "#a66f4c",
      "#955a3f",
      "#74482b",
      "#643d1e"
    ],
    "score": -7.125152587890625,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-9",
    "source": "huemint-gradient-9"
  },
  {
    "id": "fb2bdf8aa88392ae4226",
    "colors": [
      "#eecfa9",
      "#d4d6da",
      "#bfc2bf",
      "#95a4ac",
      "#72909e",
      "#788691",
      "#57656e",
      "#294966",
      "#264f61"
    ],
    "score": -7.088127136230469,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "gradient-9",
    "source": "huemint-gradient-9"
  },
  {
    "id": "96506f07bc4acb96b826",
    "colors": [
      "#ffffff",
      "#333157",
      "#4be1a3",
      "#e73060",
      "#f1b537",
      "#dcdfe4"
    ],
    "score": -6.464165210723877,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "07b4b119e5d9aa0179ed",
    "colors": [
      "#b7c6f9",
      "#302741",
      "#0089d4",
      "#e70017",
      "#e2b320",
      "#d7dbe0"
    ],
    "score": -8.997962951660156,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "537e6fc7b79b0f0eccaf",
    "colors": [
      "#ffcd00",
      "#e72277",
      "#fa870d",
      "#3090b2",
      "#e1fbdc",
      "#f5cc00"
    ],
    "score": -9.28750991821289,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "664ce5725eb181752fd4",
    "colors": [
      "#fcfffd",
      "#6744dd",
      "#fb64a3",
      "#ff308b",
      "#edb610",
      "#f5e1ec"
    ],
    "score": -9.282522201538086,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "6e7cb14c009230d9a4e8",
    "colors": [
      "#abce68",
      "#132343",
      "#e9b9cb",
      "#5a9fb6",
      "#eeddcf",
      "#85c068"
    ],
    "score": -8.759033203125,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "7b38e5379304e52bb35e",
    "colors": [
      "#efb0bb",
      "#0f1c43",
      "#4ea6ee",
      "#b54544",
      "#f4f7ff",
      "#f4a18b"
    ],
    "score": -9.097357749938965,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "8aa2b06a3aa84bc0f426",
    "colors": [
      "#f3f5fc",
      "#462d1d",
      "#009dee",
      "#d15c36",
      "#dcb99d",
      "#c56e32"
    ],
    "score": -8.948637008666992,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "b41e7db0f5a646eae428",
    "colors": [
      "#fdfdf5",
      "#0d83c9",
      "#2cc86f",
      "#e60054",
      "#eece00",
      "#eaebd3"
    ],
    "score": -7.396524429321289,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "d3f079fa20f877671b84",
    "colors": [
      "#f6f5f5",
      "#1a2131",
      "#e7589c",
      "#f32f27",
      "#63e1f1",
      "#ccdedf"
    ],
    "score": -8.66928482055664,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "ea0d9130b00aa72bc77c",
    "colors": [
      "#fcf4f1",
      "#193943",
      "#61caff",
      "#ea3a39",
      "#4a4a56",
      "#cdb3a6"
    ],
    "score": -9.208855628967285,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "825d68756423a2dab5ad",
    "colors": [
      "#fffffc",
      "#36323e",
      "#34b12e",
      "#fb5906",
      "#e8b207",
      "#d1d9d1"
    ],
    "score": -8.138790130615234,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "90b9b3d9aa2bb6d3995f",
    "colors": [
      "#fbfdfb",
      "#192541",
      "#a5a4bb",
      "#e61526",
      "#e3ac31",
      "#d3d7d8"
    ],
    "score": -7.333924293518066,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "92d939fff869769d9e61",
    "colors": [
      "#f7ffff",
      "#321747",
      "#8db5a7",
      "#e42c3b",
      "#ff9123",
      "#e6d9d9"
    ],
    "score": -7.344329357147217,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "b0a9bac48c081b0ee0dd",
    "colors": [
      "#fffffb",
      "#6a0086",
      "#74808a",
      "#cd5350",
      "#b29cc7",
      "#d5d0de"
    ],
    "score": -7.4518609046936035,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "befaa3f58a568a8f7dfd",
    "colors": [
      "#fffeff",
      "#3b2462",
      "#4290f4",
      "#ff5532",
      "#9ab13f",
      "#a3c7e9"
    ],
    "score": -7.623071193695068,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-1",
    "source": "huemint-illustration-1"
  },
  {
    "id": "3bf6d1a4e37f89a7a74a",
    "colors": [
      "#ede8da",
      "#2769a5",
      "#402527",
      "#987875",
      "#f97b67",
      "#eeaa0a",
      "#fefaf2",
      "#b8c1ac"
    ],
    "score": -9.331182479858398,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-2",
    "source": "huemint-illustration-2"
  },
  {
    "id": "558617806305aaf43fd9",
    "colors": [
      "#cdf1fa",
      "#0eaae9",
      "#165889",
      "#0d74b9",
      "#39ba92",
      "#f5cd30",
      "#e6f7eb",
      "#f7feff"
    ],
    "score": -8.341665267944336,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-2",
    "source": "huemint-illustration-2"
  },
  {
    "id": "6203aebce827fe6c1819",
    "colors": [
      "#556872",
      "#273757",
      "#b94b33",
      "#6c9b90",
      "#45aead",
      "#dbab37",
      "#08212f",
      "#b4adaa"
    ],
    "score": -9.268243789672852,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-2",
    "source": "huemint-illustration-2"
  },
  {
    "id": "73dbe513d3fe797fbae7",
    "colors": [
      "#fcffff",
      "#4e4b70",
      "#e1534e",
      "#ffc040",
      "#52afc8",
      "#fabba4",
      "#2a1e0b",
      "#babab8"
    ],
    "score": -8.820585250854492,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-2",
    "source": "huemint-illustration-2"
  },
  {
    "id": "d245ac4b2f9a3842e0d1",
    "colors": [
      "#f9fbfc",
      "#3b5689",
      "#6c67e2",
      "#263d46",
      "#83edbe",
      "#e3cd59",
      "#dbdde1",
      "#a7dfd6"
    ],
    "score": -8.662006378173828,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-2",
    "source": "huemint-illustration-2"
  },
  {
    "id": "e9dde33063bc5a1b1632",
    "colors": [
      "#fbfbfb",
      "#0a0507",
      "#461c38",
      "#ff2615",
      "#f96ed0",
      "#40ffff",
      "#73a79a",
      "#edc81d",
      "#d4db00",
      "#1af9fe",
      "#23d9de"
    ],
    "score": -7.006051063537598,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "1c12b4e73cda79e54f80",
    "colors": [
      "#f8fefe",
      "#090100",
      "#9fdf7a",
      "#dd462e",
      "#23abea",
      "#d7e2e1",
      "#6ca8e5",
      "#c8c3bb",
      "#f8d316",
      "#fff31c",
      "#46a54a"
    ],
    "score": -8.389608383178711,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "1f22b32686cb403ae78e",
    "colors": [
      "#fdffff",
      "#280045",
      "#4c2aa3",
      "#f968b4",
      "#536b76",
      "#f3ce3e",
      "#007649",
      "#77c1b7",
      "#857566",
      "#a9ce5b",
      "#fad83e"
    ],
    "score": -8.60079288482666,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "60508b2851158d395d12",
    "colors": [
      "#fdfbff",
      "#0a0726",
      "#262876",
      "#e20736",
      "#8f9fe3",
      "#fdc867",
      "#bba2af",
      "#25c9ca",
      "#539f5c",
      "#72f5b5",
      "#4be54d"
    ],
    "score": -8.499185562133789,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "7467bd234f61eacb5280",
    "colors": [
      "#fafffe",
      "#0b0b44",
      "#492098",
      "#fe408c",
      "#5eb7d2",
      "#a1cb54",
      "#61d0ff",
      "#334969",
      "#cae19a",
      "#f4bf4a",
      "#00a962"
    ],
    "score": -8.316587448120117,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "76492c6c8cc5e489430d",
    "colors": [
      "#f3543e",
      "#0df2f5",
      "#fdd818",
      "#ffaea2",
      "#f59025",
      "#8b0005",
      "#aa5415",
      "#754605",
      "#5d0001",
      "#0b0000",
      "#b7100f"
    ],
    "score": -8.563972473144531,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "9aaeec8c067147b5cfc6",
    "colors": [
      "#fafbff",
      "#25113a",
      "#a3af2b",
      "#fce7e2",
      "#009ccd",
      "#00f18c",
      "#b26a72",
      "#00cfa6",
      "#10d8b5",
      "#aef3bb",
      "#abffd6"
    ],
    "score": -8.380975723266602,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "a53fe7c9341e2b942bd0",
    "colors": [
      "#f5fbfd",
      "#00176c",
      "#0c17fa",
      "#f328f4",
      "#b8c4a0",
      "#facc71",
      "#90371c",
      "#fc7e00",
      "#fbf658",
      "#33f5f8",
      "#c3d83b"
    ],
    "score": -8.258450508117676,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "a7764be51ac917998b2c",
    "colors": [
      "#fdffff",
      "#310659",
      "#0b2a43",
      "#ea1661",
      "#50aaeb",
      "#47fbd3",
      "#df6988",
      "#fab261",
      "#f3e4aa",
      "#fbe43f",
      "#23f6f9"
    ],
    "score": -7.060959815979004,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "cb05f010fb1ebafcd8f1",
    "colors": [
      "#fffdff",
      "#222154",
      "#47265e",
      "#fb3e5a",
      "#009adf",
      "#00d6c1",
      "#eb918d",
      "#28d372",
      "#fac726",
      "#f9c100",
      "#37fb9e"
    ],
    "score": -8.021425247192383,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "61dbcbce001038e44e49",
    "colors": [
      "#f4f7fa",
      "#200848",
      "#541b3b",
      "#fd0090",
      "#558ee0",
      "#22e9e0",
      "#f87834",
      "#edac49",
      "#49cf52",
      "#e1f1cb",
      "#70f076"
    ],
    "score": -8.16411304473877,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "646f725f6dd3a4616e9e",
    "colors": [
      "#fffaff",
      "#00204b",
      "#143690",
      "#a35831",
      "#2397f5",
      "#98d347",
      "#e690ca",
      "#f5b1d2",
      "#bdcb4f",
      "#33f4fa",
      "#78bc1a"
    ],
    "score": -8.343685150146484,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "8e79e339bca9a03949a8",
    "colors": [
      "#fefffd",
      "#b66328",
      "#4f2671",
      "#5957fc",
      "#45afe3",
      "#37b837",
      "#4fc0ff",
      "#1df18a",
      "#edb843",
      "#85dd55",
      "#ebd745"
    ],
    "score": -8.538779258728027,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "9712586bb38f3084c024",
    "colors": [
      "#f8fafe",
      "#f6dbc7",
      "#008000",
      "#f80d00",
      "#06a1e3",
      "#fef501",
      "#f774bd",
      "#efdbe6",
      "#009444",
      "#00b9ff",
      "#f4e537"
    ],
    "score": -8.615382194519043,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "ccfc5ef21250f305cc9a",
    "colors": [
      "#f6f2e7",
      "#15324e",
      "#5d1d71",
      "#fb3574",
      "#acc0e5",
      "#03e0ac",
      "#03a0df",
      "#f1c436",
      "#fdef02",
      "#ddcb07",
      "#efe51f"
    ],
    "score": -8.462525367736816,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "illustration-3",
    "source": "huemint-illustration-3"
  },
  {
    "id": "3bb01a811fcb5e555958",
    "colors": [
      "#fffae6",
      "#0c304c",
      "#f85e4f"
    ],
    "score": -8.159995079040527,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-1",
    "source": "huemint-website-1"
  },
  {
    "id": "538a758b93339161669e",
    "colors": [
      "#6b1216",
      "#f0f6f4",
      "#d6ad09"
    ],
    "score": -7.933129787445068,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-1",
    "source": "huemint-website-1"
  },
  {
    "id": "695aa9a2cae4bb4bf1ec",
    "colors": [
      "#302c74",
      "#fe9825",
      "#56c3c9"
    ],
    "score": -8.251276016235352,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-1",
    "source": "huemint-website-1"
  },
  {
    "id": "6f8bce7a663caa3f6baf",
    "colors": [
      "#fdffff",
      "#14254a",
      "#d93c3c"
    ],
    "score": -5.105661869049072,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-1",
    "source": "huemint-website-1"
  },
  {
    "id": "d33061bd1376108ea8dd",
    "colors": [
      "#ece2db",
      "#353739",
      "#d74d39"
    ],
    "score": -6.278646469116211,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-1",
    "source": "huemint-website-1"
  },
  {
    "id": "1f38cea6d3937785617d",
    "colors": [
      "#242627",
      "#eff7f7",
      "#3bb7e0",
      "#ec4653"
    ],
    "score": -7.018168926239014,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-2",
    "source": "huemint-website-2"
  },
  {
    "id": "3b48479c1f2189d47406",
    "colors": [
      "#3c4046",
      "#e4e3ae",
      "#f4eee3",
      "#df5b24"
    ],
    "score": -8.105019569396973,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-2",
    "source": "huemint-website-2"
  },
  {
    "id": "4baa641931dde4e670ca",
    "colors": [
      "#2f2330",
      "#eda018",
      "#e15e26",
      "#7382cd"
    ],
    "score": -8.448047637939453,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-2",
    "source": "huemint-website-2"
  },
  {
    "id": "7dd9b9736598054f0919",
    "colors": [
      "#2e2c2d",
      "#dbe2cf",
      "#6ea099",
      "#f9775f"
    ],
    "score": -7.247353553771973,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-2",
    "source": "huemint-website-2"
  },
  {
    "id": "dddf8942a107424a2452",
    "colors": [
      "#fffeff",
      "#572c15",
      "#2fa3b3",
      "#906339"
    ],
    "score": -7.961724758148193,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-2",
    "source": "huemint-website-2"
  },
  {
    "id": "05fa8b63d67891584e7a",
    "colors": [
      "#fdcd2a",
      "#fef773",
      "#000400",
      "#120f0d",
      "#ec6a6c",
      "#fefffe"
    ],
    "score": -7.041778087615967,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-3",
    "source": "huemint-website-3"
  },
  {
    "id": "5b0b21b9301f16e80b26",
    "colors": [
      "#1ffc0d",
      "#e2f400",
      "#fe0f94",
      "#f76ff9",
      "#2e15ff",
      "#f6f100"
    ],
    "score": -7.9775004386901855,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-3",
    "source": "huemint-website-3"
  },
  {
    "id": "ed7676802e97c00efdb7",
    "colors": [
      "#121c2f",
      "#060406",
      "#f8bf0a",
      "#38bcbf",
      "#fb0709",
      "#4c30b8"
    ],
    "score": -8.123475074768066,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-3",
    "source": "huemint-website-3"
  },
  {
    "id": "f1da70f9758c84882e3b",
    "colors": [
      "#fffbfe",
      "#c6d3de",
      "#b5ffff",
      "#002dd4",
      "#f10b43",
      "#00f5be"
    ],
    "score": -7.158268928527832,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-3",
    "source": "huemint-website-3"
  },
  {
    "id": "f772fea617e437d423aa",
    "colors": [
      "#fffdff",
      "#dceced",
      "#000204",
      "#fff2dd",
      "#4144d5",
      "#00fbd4"
    ],
    "score": -7.514644145965576,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-3",
    "source": "huemint-website-3"
  },
  {
    "id": "b17ff1a0ca91e6a8daae",
    "colors": [
      "#fcfffc",
      "#fbc721",
      "#17120f",
      "#e31d28"
    ],
    "score": -6.5329694747924805,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "098401e692fe8c68e064",
    "colors": [
      "#080100",
      "#930001",
      "#fbfcfe",
      "#595e5b"
    ],
    "score": -8.48439884185791,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "2bc44ad4664280b54c5a",
    "colors": [
      "#090e0e",
      "#7300c5",
      "#f7f6f6",
      "#bea7bf"
    ],
    "score": -7.2847771644592285,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "2dc77b2cc09fc5e13641",
    "colors": [
      "#34fa68",
      "#fffffb",
      "#e60089",
      "#d64351"
    ],
    "score": -8.453352928161621,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "37ef942eda15285b6226",
    "colors": [
      "#6d79b7",
      "#123a62",
      "#f7e439",
      "#a8bacb"
    ],
    "score": -7.807961463928223,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "740713643b33a2f1d890",
    "colors": [
      "#e5e9e5",
      "#4bbcc6",
      "#0a0005",
      "#a7704b"
    ],
    "score": -7.935125350952148,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "941546410c2f01af5c44",
    "colors": [
      "#ffd4ad",
      "#9ccfb9",
      "#403f60",
      "#665e88"
    ],
    "score": -8.906632423400879,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "a86a24e6914944dff301",
    "colors": [
      "#fefbea",
      "#4ddf97",
      "#121214",
      "#f37145"
    ],
    "score": -8.110507011413574,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "b8829ee053c91c1ecfce",
    "colors": [
      "#f8ffff",
      "#59e9af",
      "#fae925",
      "#9c5add"
    ],
    "score": -8.842500686645508,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "dc6b2c11f7e274fa44aa",
    "colors": [
      "#fdd808",
      "#f5f6f4",
      "#65614d",
      "#ed110d"
    ],
    "score": -7.081482410430908,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "405ba887552f1915a47c",
    "colors": [
      "#fffefc",
      "#9fafc1",
      "#1c1a1a",
      "#264b6d"
    ],
    "score": -6.883722305297852,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "7d2af833b5ecc4d82f07",
    "colors": [
      "#fafcfd",
      "#f88c3d",
      "#271f1f",
      "#d04525"
    ],
    "score": -6.571537494659424,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "a0f37dcd456210237a1d",
    "colors": [
      "#fffeff",
      "#009fc9",
      "#040307",
      "#ffbb48"
    ],
    "score": -5.726352691650391,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "ac6dc1257cf6cf3c1f54",
    "colors": [
      "#1f2224",
      "#002d95",
      "#f4fdff",
      "#abadc9"
    ],
    "score": -6.942983150482178,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "ba29be4c542f0b3cfe46",
    "colors": [
      "#fdf5f3",
      "#c0b3ff",
      "#000100",
      "#594e8d"
    ],
    "score": -6.362675666809082,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "161bb9c716b930ea21d0",
    "colors": [
      "#070001",
      "#dac15a"
    ],
    "score": -6.245861530303955,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-monochrome",
    "source": "huemint-website-monochrome"
  },
  {
    "id": "323a0ff04a56ab2b3eb9",
    "colors": [
      "#fffdff",
      "#3b3a39"
    ],
    "score": -6.245889186859131,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-monochrome",
    "source": "huemint-website-monochrome"
  },
  {
    "id": "496726f398a79cb7d689",
    "colors": [
      "#fdfffe",
      "#1d4476"
    ],
    "score": -4.836363792419434,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-monochrome",
    "source": "huemint-website-monochrome"
  },
  {
    "id": "aa5a1506c4616cb203ac",
    "colors": [
      "#00304e",
      "#e7c57f"
    ],
    "score": -6.849468231201172,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-monochrome",
    "source": "huemint-website-monochrome"
  },
  {
    "id": "de1bde05fc0e6db21450",
    "colors": [
      "#f4f8f7",
      "#373537"
    ],
    "score": -4.761748790740967,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-monochrome",
    "source": "huemint-website-monochrome"
  }
];
