// Generated by npm run huemint:browser-corpus. Do not edit by hand.
window.HUEMINT_LOCAL_CORPUS = [
  {
    "id": "b17ff1a0ca91e6a8daae",
    "colors": [
      "#fcfffc",
      "#fbc721",
      "#17120f",
      "#e31d28"
    ],
    "score": -6.5329694747924805,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "098401e692fe8c68e064",
    "colors": [
      "#080100",
      "#930001",
      "#fbfcfe",
      "#595e5b"
    ],
    "score": -8.48439884185791,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "2bc44ad4664280b54c5a",
    "colors": [
      "#090e0e",
      "#7300c5",
      "#f7f6f6",
      "#bea7bf"
    ],
    "score": -7.2847771644592285,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "2dc77b2cc09fc5e13641",
    "colors": [
      "#34fa68",
      "#fffffb",
      "#e60089",
      "#d64351"
    ],
    "score": -8.453352928161621,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "37ef942eda15285b6226",
    "colors": [
      "#6d79b7",
      "#123a62",
      "#f7e439",
      "#a8bacb"
    ],
    "score": -7.807961463928223,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "740713643b33a2f1d890",
    "colors": [
      "#e5e9e5",
      "#4bbcc6",
      "#0a0005",
      "#a7704b"
    ],
    "score": -7.935125350952148,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "941546410c2f01af5c44",
    "colors": [
      "#ffd4ad",
      "#9ccfb9",
      "#403f60",
      "#665e88"
    ],
    "score": -8.906632423400879,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "a86a24e6914944dff301",
    "colors": [
      "#fefbea",
      "#4ddf97",
      "#121214",
      "#f37145"
    ],
    "score": -8.110507011413574,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "b8829ee053c91c1ecfce",
    "colors": [
      "#f8ffff",
      "#59e9af",
      "#fae925",
      "#9c5add"
    ],
    "score": -8.842500686645508,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  },
  {
    "id": "dc6b2c11f7e274fa44aa",
    "colors": [
      "#fdd808",
      "#f5f6f4",
      "#65614d",
      "#ed110d"
    ],
    "score": -7.081482410430908,
    "generator": "transformer",
    "creativity": 1.3,
    "preset": "default",
    "template": "website-magazine",
    "source": "huemint-website-magazine"
  }
];
